module.exports = {
    MANAGE_SUBMISSIONS: 'MANAGE_SUBMISSIONS',
    MANAGE_POLISH_SUBMISSIONS: 'MANAGE_POLISH_SUBMISSIONS',
    MANAGE_BRAND_SUBMISSIONS: 'MANAGE_BRAND_SUBMISSIONS',
    MANAGE_ROLES: 'MANAGE_ROLES',
    UPLOAD_DUPE: 'UPLOAD_DUPE',
    UPLOAD_POLISH: 'UPLOAD_POLISH',
    UPLOAD_BRAND: 'UPLOAD_BRAND',
};
